### ISSUE TITLE
admin-files as a permission type?

### ISSUE THREAD

**Issue by jsumnersmith** [apostrophecms-legacy/apostrophe-groups#7]
I tried adding a permission "admin-files" explicitly in mongo, but it doesn't seem to have any effect. The goal is to allow certain groups of people to be admins of the media library. Does that make sense?

**Comment by boutell** [comment]
try admin-file (singular)

On Wed, Jan 21, 2015 at 8:48 AM, Joel Smith <notifications@github.com>
wrote:

> I tried adding a permission "admin-files" explicitly in mongo, but it
> doesn't seem to have any effect. The goal is to allow certain groups of
> people to be admins of the media library. Does that make sense?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/apostrophe-groups/issues/7>.
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by jsumnersmith** [comment]
Nailed it.
